// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01ZMBjiPui8nF3JmdBD4VpAEr-jm9a1Y',
    appId: '1:56718263229:web:21438d4ac181c7a5a408d4',
    messagingSenderId: '56718263229',
    projectId: 'flutter-prac-1-a6859',
    authDomain: 'flutter-prac-1-a6859.firebaseapp.com',
    storageBucket: 'flutter-prac-1-a6859.firebasestorage.app',
    measurementId: 'G-HJ08YV6Q87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jvVS0BHG0909UVn7MaEd6DUul3HA0KI',
    appId: '1:56718263229:android:f4e599ec4c39384da408d4',
    messagingSenderId: '56718263229',
    projectId: 'flutter-prac-1-a6859',
    storageBucket: 'flutter-prac-1-a6859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7Hh7iQHjEGidBDUOv5BcIpHeU58rTew',
    appId: '1:56718263229:ios:f1ac052ae5f42ac3a408d4',
    messagingSenderId: '56718263229',
    projectId: 'flutter-prac-1-a6859',
    storageBucket: 'flutter-prac-1-a6859.firebasestorage.app',
    iosBundleId: 'com.prac1.flutterPrac1',
  );
}
